version: "3"

services:
  web:
    build: .
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    stdin_open: true
    tty: true
    networks:
      - syncopate
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - local.env
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    networks:
      - syncopate
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_password
    ports:
      - 27017:27017

networks:
  syncopate: